name: pon
description: pon
homepage: https://github.com/TheAlphamerc/flutter_plugin_filter_list

#

#

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 1.0.3+2
  shared_preferences: ^0.5.4+6
  pin_code_text_field: ^1.3.7
  provider: ^4.1.3
  cached_network_image: ^2.0.0-rc.1
  device_info: ^0.4.1+4
  flutter_datetime_picker: ^1.2.0
  package_info: ^0.4.0+14
  image_picker: ^0.6.3+4
  fluttertoast: ^3.1.3
  url_launcher: 5.1.3
  flutter_swiper: ^1.1.6
  page_view_indicators: ^1.3.1
  transformer_page_view: ^0.1.6
  intl: ^0.16.0
  webview_flutter: ^0.3.16
  flutter_secure_storage: ^3.3.1+1
  razorpay_flutter: ^1.1.1
  flutter_plugin_pdf_viewer: ^1.0.7
  filter_list: ^0.0.5
  pdf: ^1.3.24
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.5.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5

flutter_native_splash:
  color: "002539"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
  - assets/images/


fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 500
